services:

  db:
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql  # Mount the SQL file
    ports:
      - "3307:3306"  # Maps port 3306 in the container to port 3306 on the host

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # Maps port 80 in the container to port 3000 on the host
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Maps port 8000 in the container to port 8000 on the host
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db
