services:

  db:
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db.sql:/app/db.sql  # Mount the SQL file for database population
    ports:
      - "3307:3306"  # Maps port 3306 in the container to port 3306 on the host
    healthcheck:
        test: ["CMD", "sh", "-c", "env MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]    
        interval: 5s
        timeout: 5s
        retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # Maps port 80 in the container to port 3000 on the host
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Maps port 8000 in the container to port 8000 on the host
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DJANGO_SUPERUSER_USERNAME=root  # Username for the superuser
      - DJANGO_SUPERUSER_EMAIL=root@localhost  # Superuser email
      - DJANGO_SUPERUSER_PASSWORD=pass  # Superuser password
    depends_on:
      db:
        condition: service_healthy
