services:

  db:
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fakzapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    healthcheck:
        test: ["CMD", "sh", "-c", "env MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]    
        interval: 5s
        timeout: 5s
        retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:80"  # Maps port 80 in the container to port 3000 on the host
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Maps port 8000 in the container to port 8000 on the host
    environment:
      DB_HOST: db # Database service is named db
      DB_NAME: fakzapp # Database name to use
      DB_USER: root
      DB_PASSWORD: pass
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: root@localhost
      DJANGO_SUPERUSER_PASSWORD: pass
    volumes:
      - ./initial_data.json:/app/initial_data.json  # Mount initial_data.json into the /app directory in the container
    depends_on:
      db:
        condition: service_healthy
